import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { WORLD_EXTENT, projectWorldPoint } from "../src/map-projection.ts";

// Rebuild entirely from the checked-in, unmodified public-domain source.
// No network access or GIS dependency is needed.
const source = readFileSync(new URL("../vendor/natural-earth/ne_110m_land.geojson", import.meta.url));
const sourceHash = "9e0729ee253ca7d7a5c4ae9395fb1902264c5377c52e224d13dd85010e2835d9";
if (createHash("sha256").update(source).digest("hex") !== sourceHash) {
  throw new Error("Natural Earth source changed; review its provenance before regenerating.");
}
const land = JSON.parse(source.toString()) as {
  features: { geometry: { type: string; coordinates: [number, number][][] } }[];
};
const paths = land.features.map(({ geometry }) => {
  if (geometry.type !== "Polygon") throw new Error(`Unexpected geometry: ${geometry.type}`);
  const d = geometry.coordinates.map((ring) => {
    const points = ring.map(([longitude, latitude]) => {
      const { x, y } = projectWorldPoint(latitude, longitude);
      return `${Number(x.toFixed(3))},${Number(y.toFixed(3))}`;
    });
    return `M${points.join("L")}Z`;
  }).join("");
  return `  <path d="${d}"/>`;
});
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WORLD_EXTENT.width} ${WORLD_EXTENT.height}" width="${WORLD_EXTENT.width}" height="${WORLD_EXTENT.height}">
  <title>World land outlines</title>
  <desc>Natural Earth 1:110 million land. Equirectangular projection, longitude -180 to 180, latitude 90 to -90. Generalized coastlines including major islands.</desc>
  <metadata>Made with Natural Earth. Public domain. https://www.naturalearthdata.com/about/terms-of-use/ Source: nvkelso/natural-earth-vector v5.1.2/geojson/ne_110m_land.geojson. SHA-256: ${sourceHash}. Generated by scripts/build_world_map.ts; upstream data, provenance and full license are retained in vendor/natural-earth/.</metadata>
  <g fill="#315b60" stroke="#779b97" stroke-width="0.22" stroke-linejoin="round" fill-rule="evenodd">
${paths.join("\n")}
  </g>
</svg>
`;
const destination = new URL("../src/assets/natural-earth-land.svg", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== svg) throw new Error("World basemap is stale; run npm run map:build.");
  console.log(`World basemap matches all ${paths.length} source polygons.`);
} else {
  writeFileSync(destination, svg);
  console.log(`Generated world basemap with ${paths.length} land polygons.`);
}
