"""Normalize the reviewed supplier catalog without discarding field-level evidence."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
x=json.loads((root/'research/uwh_suppliers.json').read_text())
kinds={'manufacturer_and_reseller':'Manufacturer & retailer','specialist_retailer_with_own_brand':'Retailer · own-brand range','specialist_retailer':'Retailer','multi_brand_retailer':'Retailer','product_developer_and_reseller':'Product developer & retailer','association_operated_retailer':'Association retailer','manufacturer_with_reseller_network':'Manufacturer','general_dive_manufacturer_and_supplier':'Manufacturer & supplier','cap_manufacturer_and_underwater_sports_retailer':'Cap manufacturer & retailer'}
labels={'sticks':'Sticks','gloves':'Gloves','fins':'Fins','masks':'Masks','snorkels':'Snorkels','caps':'Caps','mouthguards':'Mouthguards','pucks':'Pucks','goals':'Goals','club_equipment':'Club equipment'}
rows=[]
for s in x['suppliers']:
 rows.append(dict(id=s['id'],name=s['name'],country=s['country']['name'],categories=[labels[k] for k in s['categories']],kind=kinds[s['businessModel']],url=s['url'],canadaShipping=s['canadaShipping']['label'],shippingEvidence=s['canadaShipping']['evidence'],customOrders=s['customOrders']['description'],clubOrders=s['clubOrders']['description'],checked=s['checkedAt'],sourceUrl=s['url'],note=s['description'],sourceIds=s['sourceIds'],notes=s['notes'],verification=s['verification']['meaning'],rawSupplier=s))
head='''// Generated by scripts/import_suppliers.py from the reviewed original catalog.
export interface SupplierSource { id: string; title: string; url: string; publicCitationUrl?: string; publisherType: string; checkedAt: string; access: string; evidenceSummary: string; accessNote?: string }
export interface Supplier { id:string; name:string; country:string; categories:string[]; kind:string; url:string; canadaShipping:string; shippingEvidence:string; customOrders:string; clubOrders:string; checked:string; sourceUrl:string; note:string; sourceIds:string[]; notes:string[]; verification:string; rawSupplier:Record<string,unknown> }
'''
head+='export const supplierSources: SupplierSource[] = '+json.dumps(x['sources'],ensure_ascii=False,indent=2)+';\n'
head+='export const suppliers: Supplier[] = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n'
head+='export const supplierNotice = '+json.dumps(x['publicNotice'])+';\n'
(root/'src/suppliers.ts').write_text(head)
print(f"Imported {len(rows)} suppliers and {len(x['sources'])} source observations")
